import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { AppHeaderNav } from "@/components/AppHeaderNav";
import { AppHeaderSignOut } from "@/components/AppHeaderSignOut";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground min-h-screen`}
      >
        <header className="w-full border-b bg-white/80 backdrop-blur sticky top-0 z-30 shadow-sm">
          <div className="max-w-5xl mx-auto flex items-center justify-between px-6 py-3">
            {/* Left: Logo and app name */}
            <div className="flex items-center gap-3">
              <Link href="/" className="flex items-center gap-2">
                <Image
                  src="/digestly_logo.png"
                  alt="Digestly Logo"
                  width={36}
                  height={36}
                  className="mr-2"
                  priority
                />
                <span className="font-bold text-xl tracking-tight text-blue-700">
                  Digestly
                </span>
              </Link>
            </div>
            {/* Right: Menu and sign out */}
            <div className="flex items-center gap-4">
              <AppHeaderNav />
              <AppHeaderSignOut />
            </div>
          </div>
        </header>
        <main className="max-w-5xl mx-auto px-4 py-8">{children}</main>
      </body>
    </html>
  );
}
