import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Digestly",
  description: "Terms and conditions for using the Digestly service.",
};

export default function TermsOfServicePage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>

      <div className="prose prose-slate max-w-none">
        <p className="text-gray-500 mb-8">Last updated: June 25, 2025</p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
          <p>
            Welcome to Digestly (&ldquo;Company&rdquo;, &ldquo;we&rdquo;,
            &ldquo;our&rdquo;, &ldquo;us&rdquo;)! As you have just clicked our
            Terms of Service, please read these Terms of Service carefully
            before using our application.
          </p>
          <p className="mt-4">
            These Terms of Service explain the terms by which you may use our
            website and service for delivering digests from your Notion
            databases. By accessing or using the Digestly application, you agree
            to be bound by these Terms of Service and our Privacy Policy.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">2. Definitions</h2>
          <p>
            <strong>Service</strong> refers to the application provided by
            Digestly.
          </p>
          <p className="mt-2">
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </p>
          <p className="mt-2">
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">3. Your Account</h2>
          <p>
            When you create an account with us, you must provide accurate and
            complete information. You are responsible for safeguarding the
            password that you use to access the Service and for any activities
            or actions under your password.
          </p>
          <p className="mt-4">
            You agree not to disclose your password to any third party. You must
            notify us immediately upon becoming aware of any breach of security
            or unauthorized use of your account.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">4. Use of the Service</h2>
          <p>
            Our Service allows you to connect your Notion account and receive
            email digests from your selected databases. You agree to use the
            Service only for purposes that are permitted by:
          </p>
          <ul className="list-disc pl-6 mb-4 mt-4">
            <li className="mb-2">These Terms</li>
            <li className="mb-2">
              Applicable law, regulation, or generally accepted practices or
              guidelines
            </li>
          </ul>
          <p>
            You agree not to engage in any of the following prohibited
            activities:
          </p>
          <ul className="list-disc pl-6 mb-4 mt-4">
            <li className="mb-2">
              Copying, distributing, or disclosing any part of the Service in
              any medium
            </li>
            <li className="mb-2">
              Using any automated system to access the Service in a manner that
              sends more request messages than a human can reasonably produce
            </li>
            <li className="mb-2">
              Interfering with or disrupting the integrity or performance of the
              Service or related data
            </li>
            <li className="mb-2">
              Attempting to decipher, decompile, disassemble, or reverse
              engineer any of the software used to provide the Service
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">5. Notion Integration</h2>
          <p>
            Our Service integrates with Notion to retrieve data from your
            databases. By using Digestly, you authorize us to access the
            specific databases you select within your Notion account. We will
            only access the data you explicitly grant us permission to access.
          </p>
          <p className="mt-4">
            You understand that your use of Notion is governed by Notion&apos;s
            own Terms of Service and Privacy Policy. We are not responsible for
            any changes, interruptions, or discontinuation of Notion&apos;s
            services that may affect Digestly.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            6. Intellectual Property
          </h2>
          <p>
            The Service and its original content, features, and functionality
            are and will remain the exclusive property of Digestly and its
            licensors. The Service is protected by copyright, trademark, and
            other intellectual property laws.
          </p>
          <p className="mt-4">
            Our trademarks and trade dress may not be used in connection with
            any product or service without the prior written consent of
            Digestly.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">7. User Content</h2>
          <p>
            You retain all your rights to any content that you submit, post, or
            display on or through the Service. By providing content to the
            Service, you grant us a worldwide, non-exclusive, royalty-free
            license to use, reproduce, adapt, publish, translate, and distribute
            your content in connection with the Service.
          </p>
          <p className="mt-4">
            You are solely responsible for the content that you share through
            the Service, including its legality, reliability, and
            appropriateness.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            8. Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by law, in no event shall Digestly,
            nor its directors, employees, partners, agents, suppliers, or
            affiliates, be liable for any indirect, incidental, special,
            consequential, or punitive damages, including without limitation,
            loss of profits, data, use, goodwill, or other intangible losses,
            resulting from:
          </p>
          <ul className="list-disc pl-6 mb-4 mt-4">
            <li className="mb-2">
              Your access to or use of or inability to access or use the Service
            </li>
            <li className="mb-2">
              Any conduct or content of any third party on the Service
            </li>
            <li className="mb-2">Any content obtained from the Service</li>
            <li className="mb-2">
              Unauthorized access, use, or alteration of your transmissions or
              content
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">9. Disclaimer</h2>
          <p>
            Your use of the Service is at your sole risk. The Service is
            provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
            warranties of any kind, either express or implied, including, but
            not limited to, implied warranties of merchantability, fitness for a
            particular purpose, non-infringement, or course of performance.
          </p>
          <p className="mt-4">
            Digestly does not warrant that a) the Service will function
            uninterrupted, secure, or available at any particular time or
            location; b) any errors or defects will be corrected; c) the Service
            is free of viruses or other harmful components; or d) the results of
            using the Service will meet your requirements.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">10. Termination</h2>
          <p>
            We may terminate or suspend your account immediately, without prior
            notice or liability, for any reason whatsoever, including, without
            limitation, if you breach the Terms.
          </p>
          <p className="mt-4">
            Upon termination, your right to use the Service will immediately
            cease. If you wish to terminate your account, you may simply
            discontinue using the Service, or you may contact us to request
            account deletion.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">11. Governing Law</h2>
          <p>
            These Terms shall be governed and construed in accordance with the
            laws, without regard to its conflict of law provisions.
          </p>
          <p className="mt-4">
            Our failure to enforce any right or provision of these Terms will
            not be considered a waiver of those rights. If any provision of
            these Terms is held to be invalid or unenforceable by a court, the
            remaining provisions of these Terms will remain in effect.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">12. Changes to Terms</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace
            these Terms at any time. If a revision is material, we will try to
            provide at least 30 days notice prior to any new terms taking
            effect.
          </p>
          <p className="mt-4">
            By continuing to access or use our Service after those revisions
            become effective, you agree to be bound by the revised terms. If you
            do not agree to the new terms, please stop using the Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">13. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at{" "}
            <a
              href="mailto:knockanapp@gmail.com"
              className="text-blue-700 hover:underline"
            >
              knockanapp@gmail.com
            </a>
          </p>
        </section>
      </div>

      <div className="mt-12 pt-6 border-t border-gray-200">
        <Link href="/" className="text-blue-700 hover:underline">
          &larr; Return to Home
        </Link>
      </div>
    </div>
  );
}
